### ISSUE TITLE
Legacy tokens deprecated

### ISSUE THREAD

**Issue by crevulus** [mpangrazzi/spotify-status-on-slack#1]
Is there an alternative to the legacy token setting step? Or perhaps a use-all legacy token we could use? Currently that step is blocking as [legacy tokens are deprecated](https://api.slack.com/legacy/custom-integrations/legacy-tokens).

**Comment by mpangrazzi** [comment]
Hmm... According to [their docs](https://slack.com/intl/en-it/help/articles/215770388-Create-and-regenerate-API-tokens) the only way to get rid of legacy tokens is to create a Slack App. I'll look into it when I'll have some free time.

**Comment by crevulus** [comment]
No rush, and cheers for looking into it.

**Comment by HiddenWalrus** [comment]
Would also love to see this! Thanks so much for looking into it!

**Comment by jerechinsky** [comment]
This guy described how to get a legacy token. https://dev.to/aedenmurray/share-your-music-in-slack-3g4m

Also this project might interest you. https://github.com/giorgimode/SpotMyStatus/

**Comment by mpangrazzi** [comment]
Actually, after checking I would say that I don't like the idea to build a Spotify app (which needs to be approved on your workspace, requires permissions, and so on) to do such a simple thing on a single user account.

**Comment by crevulus** [comment]
No worries, will close issue.
